#!/usr/bin/env node
/**
 * emit/tailwind-theme.mjs — first emitter in the DesignTokenIR pipeline.
 *
 * Pure transform:  tokens/resolved.<theme>.json  →  generated/design-tokens.js
 *
 * Emits a CommonJS module (tailwind.config.js is CommonJS) exposing:
 *   - colors       nested Tailwind theme.extend.colors map, byte-compatible with the
 *                  legacy `designSystem.themeColors` naming so existing Pug/Sass
 *                  utility classes (text-primary-1, bg-grey-950, …) keep working.
 *   - fontFamily   family stacks keyed by role + token (font-<Family>), derived from
 *                  the IR font tokens.
 *   - meta         provenance (theme, source + resolved fingerprints).
 *
 * This retires the "dual color authority" flaw: tailwind.config.js stops carrying
 * token values and instead imports this generated artifact. The file is 100%
 * generated — never hand-edit. Determinism: sorted keys, no timestamps.
 *
 * Usage:
 *   node automation/emit/tailwind-theme.mjs                 # → generated/design-tokens.js
 *   node automation/emit/tailwind-theme.mjs --theme base
 *   node automation/emit/tailwind-theme.mjs --check         # CI: fail if stale
 */
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { readJson, stableStringify, tailwindColorName } from "../ir/lib/ir-utils.mjs";

const ROOT = process.cwd();
const argv = process.argv.slice(2);
const CHECK_ONLY = argv.includes("--check");
const THEME = (() => {
	const i = argv.indexOf("--theme");
	return i !== -1 && argv[i + 1] ? argv[i + 1] : "base";
})();
const BUNDLE_PATH = path.join(ROOT, `tokens/resolved.${THEME}.json`);
const OUT_PATH = path.join(ROOT, "generated/design-tokens.js");

/** Nest a flat tailwind name into { group: { shade } } / { name: { DEFAULT } }. */
function nestColor(target, name, value) {
	const dash = name.indexOf("-");
	if (dash === -1) {
		(target[name] ??= {}).DEFAULT = value;
	} else {
		const g = name.slice(0, dash);
		const s = name.slice(dash + 1);
		(target[g] ??= {})[s] = value;
	}
}

function buildColors(bundle) {
	const colors = {};
	for (const c of Object.values(bundle.colors)) {
		nestColor(colors, tailwindColorName(c.group, c.scale), c.value);
	}
	// Semantic aliases as top-level utilities (role → resolved hex).
	for (const s of Object.values(bundle.semantics)) {
		if (!(s.role in colors)) colors[s.role] = s.value;
	}
	return colors;
}

function buildFontFamily(bundle) {
	const fontFamily = {};
	for (const f of Object.values(bundle.fonts)) {
		const stack = f.stack.split(",").map((p) => p.trim()).filter(Boolean);
		// Role alias (sans/serif/display/icon) + explicit family alias (font-<Family>).
		if (!(f.role in fontFamily)) fontFamily[f.role] = stack;
		const familyKey = f.family.replace(/\s+/g, "-");
		fontFamily[familyKey] = stack;
	}
	return fontFamily;
}

function render(bundle) {
	const payload = {
		colors: buildColors(bundle),
		fontFamily: buildFontFamily(bundle),
		meta: {
			theme: bundle.theme,
			source: bundle.meta.source,
			bundleVersion: bundle.meta.bundleVersion,
			sourceFingerprint: bundle.meta.sourceFingerprint,
			resolvedFingerprint: bundle.meta.fingerprint,
		},
	};
	const banner =
		"// AUTO-GENERATED by automation/emit/tailwind-theme.mjs — DO NOT EDIT.\n" +
		`// Source: tokens/resolved.${THEME}.json (${bundle.meta.fingerprint})\n` +
		"// Regenerate: npm run emit:tailwind\n";
	return `${banner}module.exports = ${stableStringify(payload)};\n`;
}

function main() {
	if (!fs.existsSync(BUNDLE_PATH)) {
		console.error(`❌ Missing ${path.relative(ROOT, BUNDLE_PATH)} — run: npm run ir:resolve`);
		process.exit(1);
	}
	const bundle = readJson(BUNDLE_PATH);
	const text = render(bundle);

	const colorGroups = Object.keys(buildColors(bundle)).sort();
	console.log("🎨 emit tailwind-theme");
	console.log(`   theme         ${bundle.theme}`);
	console.log(`   color groups  ${colorGroups.length} (${colorGroups.join(", ")})`);
	console.log(`   font aliases  ${Object.keys(buildFontFamily(bundle)).length}`);

	if (CHECK_ONLY) {
		const prev = fs.existsSync(OUT_PATH) ? fs.readFileSync(OUT_PATH, "utf8") : "";
		if (prev !== text) {
			console.error(`\n❌ ${path.relative(ROOT, OUT_PATH)} is stale. Run: npm run emit:tailwind`);
			process.exit(1);
		}
		console.log(`   ✅ ${path.relative(ROOT, OUT_PATH)} up to date`);
		return;
	}

	fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
	fs.writeFileSync(OUT_PATH, text, "utf8");
	console.log(`   └── wrote ${path.relative(ROOT, OUT_PATH)}`);
}

main();
